### ISSUE TITLE
Syntax Error...

### ISSUE THREAD

**Issue by umgeher** [jbrisbin/amqp_client#37]
![2016-11-29-205043_537x600_scrot](https://cloud.githubusercontent.com/assets/224185/20728416/83be66de-b675-11e6-8172-f4a6840c9ea4.png)

[compile.txt](https://github.com/jbrisbin/amqp_client/files/620157/compile.txt)

My rebar.config: 

```erlang
{erl_opts, [debug_info]}.

{deps, [
	{amqp_client, ".*", {git, "git://github.com/jbrisbin/amqp_client.git", {tag, "rabbitmq-3.5.6-community"}}}
       ]
}.
```

**Comment by alexdesousa** [comment]
@umgeher probably you're trying to compile with Erlang 19 and version 3.5.6 is not compatible with Erlang 19.
